
#ifndef _MAIN_H_
#define _MAIN_H_


#define	OS_TICKS_PER_MILLI		5

#define	DLY_MS( _ms)			( _ms*OS_TICKS_PER_MILLI)

#define		_PHY_IS_T1_			0

#define USER_FLASH_FIRST_PAGE_ADDRESS 0x08040000 /* Only as example see comment */
#define USER_FLASH_LAST_PAGE_ADDRESS  0x080CFFFF
#define BACKUP_FLASH_FIRST_PAGE_ADDRESS  0x08100000
#define BACKUP_FLASH_LAST_PAGE_ADDRESS  0x081BFFFF
#define USER_FLASH_END_ADDRESS        0x081BFFFF

#endif

